from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List


@dataclass(frozen=True)
class EntityUiConfig:
    default_visible: List[str]
    default_sort: List[dict]
    title: str


ENTITY_UI_CONFIG: Dict[str, EntityUiConfig] = {
    "person": EntityUiConfig(
        title="人员",
        default_visible=[
            "person_id",
            "name_original",
            "name_norm",
            "orcid",
            "country",
            "chinese_identity",
            "current_affiliation",
            "qs_top200_rank",
            "world_top500_rank",
            "h_index",
            "total_citations",
            "updated_at",
        ],
        default_sort=[{"field": "updated_at", "order": "desc"}],
    ),
    "publication": EntityUiConfig(
        title="论文",
        default_visible=[
            "publication_id",
            "title",
            "doi",
            "publication_year",
            "source_title",
            "document_type",
            "times_cited_all_db",
            "updated_at",
        ],
        default_sort=[{"field": "publication_year", "order": "desc"}],
    ),
    "person_publication": EntityUiConfig(
        title="人员-论文关系",
        default_visible=[
            "relation_id",
            "person_id",
            "publication_id",
            "relation_type",
            "author_order",
            "match_score",
            "match_confidence",
            "updated_at",
        ],
        default_sort=[{"field": "updated_at", "order": "desc"}],
    ),
    "author_occurrence": EntityUiConfig(
        title="作者出现记录",
        default_visible=[
            "occurrence_id",
            "publication_id",
            "author_order",
            "author_name_raw",
            "orcid",
            "chinese_identity",
            "is_corresponding_author",
            "updated_at",
        ],
        default_sort=[{"field": "author_order", "order": "asc"}],
    ),
    "author_identifier_claim": EntityUiConfig(
        title="作者标识声明",
        default_visible=[
            "claim_id",
            "occurrence_id",
            "publication_id",
            "claim_type",
            "claim_value",
            "confidence",
            "score",
            "updated_at",
        ],
        default_sort=[{"field": "updated_at", "order": "desc"}],
    ),
    "author_affiliation_claim": EntityUiConfig(
        title="作者机构声明",
        default_visible=[
            "claim_id",
            "occurrence_id",
            "publication_id",
            "institution",
            "country_norm",
            "qs_top200_rank",
            "world_top500_rank",
            "is_reprint",
            "confidence",
            "updated_at",
        ],
        default_sort=[{"field": "updated_at", "order": "desc"}],
    ),
    "author_email_claim": EntityUiConfig(
        title="作者邮箱声明",
        default_visible=[
            "claim_id",
            "occurrence_id",
            "publication_id",
            "email",
            "email_domain",
            "world_top500_rank",
            "binding_rule",
            "confidence",
            "updated_at",
        ],
        default_sort=[{"field": "updated_at", "order": "desc"}],
    ),
}


EXACT_CN_LABELS: Dict[str, str] = {
    "original_id": "原始记录ID",
    "person_id": "人员ID",
    "canonical_person_id": "规范人员ID",
    "legacy_person_id": "历史人员ID",
    "name_original": "姓名",
    "name_norm": "规范姓名",
    "name_aliases": "姓名别名",
    "matched_by_orcid": "是否由ORCID归并",
    "orcid": "ORCID",
    "researcher_ids": "Researcher IDs",
    "country": "国家",
    "countries_observed": "观测国家列表",
    "current_affiliation": "当前机构",
    "chinese_identity": "华人华裔分类",
    "qs_top200_rank": "QS前200排名",
    "world_top500_rank": "世界500强排名",
    "affiliations": "机构列表",
    "addresses": "地址列表",
    "primary_email": "主邮箱",
    "emails": "邮箱列表",
    "subjects": "学科领域",
    "keywords": "关键词",
    "interests": "研究兴趣",
    "h_index": "H指数",
    "i10_index": "i10指数",
    "total_citations": "总被引次数",
    "average_citations": "平均被引次数",
    "articles": "论文数",
    "google_scholar_url": "Google Scholar链接",
    "sci_profile_url": "Sci Profile链接",
    "match_methods": "匹配方法",
    "cluster_size": "聚类规模",
    "source_systems": "来源系统",
    "source_refs": "来源引用",
    "source_refs.source_system": "来源系统",
    "source_refs.source_file": "来源文件",
    "source_refs.sheet": "来源工作表",
    "source_refs.row_index": "来源行号",
    "source_refs.raw_keys": "来源原始字段",
    "created_at": "创建时间",
    "updated_at": "更新时间",
    "publication_id": "论文ID",
    "doi": "DOI",
    "doi_link": "DOI链接",
    "ut_wos_id": "WoS唯一ID",
    "pubmed_id": "PubMed ID",
    "title": "标题",
    "abstract": "摘要",
    "document_type": "文档类型",
    "publication_type": "发表类型",
    "publication_year": "发表年份",
    "publication_date_text": "发表日期文本",
    "volume": "卷",
    "issue": "期",
    "article_number": "文章编号",
    "number_of_pages": "页数",
    "source_title": "来源刊物",
    "journal_abbr": "期刊缩写",
    "journal_iso_abbr": "期刊ISO缩写",
    "issn": "ISSN",
    "eissn": "eISSN",
    "language": "语言",
    "publisher": "出版社",
    "publisher_city": "出版城市",
    "publisher_address": "出版地址",
    "author_keywords": "作者关键词",
    "keywords_plus": "Keywords Plus",
    "wos_categories": "WoS分类",
    "research_areas": "研究领域",
    "web_of_science_index": "Web of Science索引",
    "times_cited_wos_core": "WoS Core被引次数",
    "times_cited_all_db": "全库被引次数",
    "usage_180d": "180天使用次数",
    "usage_since_2013": "2013年以来使用次数",
    "open_access_designation": "开放获取标识",
    "funding_orgs": "资助机构",
    "funding_text": "资助文本",
    "relation_id": "关系ID",
    "relation_type": "关系类型",
    "author_order": "作者序号",
    "author_name_in_paper": "论文作者名",
    "match_score": "匹配分数",
    "match_confidence": "匹配置信度",
    "match_rules_hit": "命中规则",
    "is_corresponding_author": "是否通讯作者",
    "occurrence_id": "出现记录ID",
    "author_name_raw": "作者原始姓名",
    "author_name_norm": "作者规范姓名",
    "surname_norm": "姓氏规范值",
    "given_names_norm": "名字规范值",
    "initials": "姓名首字母",
    "claim_id": "声明ID",
    "claim_type": "声明类型",
    "claim_value": "声明值",
    "matched_name_raw": "匹配姓名原文",
    "match_rule": "匹配规则",
    "confidence": "置信度",
    "score": "分数",
    "source_field": "来源字段",
    "institution": "机构",
    "address_text": "地址文本",
    "country_raw": "原始国家",
    "country_norm": "规范国家",
    "is_reprint": "是否重印地址",
    "email": "邮箱",
    "email_domain": "邮箱域名",
    "local_part": "邮箱本地部分",
    "binding_rule": "绑定规则",
}


TOKEN_CN_LABELS: Dict[str, str] = {
    "original": "原始",
    "canonical": "规范",
    "legacy": "历史",
    "person": "人员",
    "publication": "论文",
    "author": "作者",
    "occurrence": "出现",
    "claim": "声明",
    "relation": "关系",
    "name": "姓名",
    "norm": "规范",
    "aliases": "别名",
    "matched": "匹配",
    "by": "按",
    "country": "国家",
    "countries": "国家",
    "observed": "观测",
    "current": "当前",
    "affiliation": "机构",
    "affiliations": "机构",
    "address": "地址",
    "addresses": "地址",
    "primary": "主",
    "email": "邮箱",
    "emails": "邮箱",
    "subjects": "学科",
    "keywords": "关键词",
    "interests": "兴趣",
    "google": "Google",
    "scholar": "Scholar",
    "url": "链接",
    "source": "来源",
    "systems": "系统",
    "refs": "引用",
    "file": "文件",
    "sheet": "工作表",
    "row": "行",
    "index": "索引",
    "created": "创建",
    "updated": "更新",
    "title": "标题",
    "abstract": "摘要",
    "document": "文档",
    "type": "类型",
    "year": "年份",
    "date": "日期",
    "text": "文本",
    "volume": "卷",
    "issue": "期",
    "number": "编号",
    "pages": "页数",
    "journal": "期刊",
    "iso": "ISO",
    "language": "语言",
    "publisher": "出版社",
    "city": "城市",
    "funding": "资助",
    "orgs": "机构",
    "wos": "WoS",
    "times": "次数",
    "cited": "被引",
    "all": "全量",
    "db": "库",
    "usage": "使用",
    "open": "开放",
    "access": "获取",
    "designation": "标识",
    "order": "序号",
    "paper": "论文",
    "rules": "规则",
    "hit": "命中",
    "corresponding": "通讯",
    "surname": "姓氏",
    "given": "名字",
    "names": "姓名",
    "initials": "首字母",
    "value": "值",
    "field": "字段",
    "institution": "机构",
    "raw": "原始",
    "reprint": "重印",
    "domain": "域名",
    "local": "本地",
    "part": "部分",
    "binding": "绑定",
    "methods": "方法",
    "cluster": "聚类",
    "size": "规模",
    "qs": "QS",
    "top": "Top",
    "world": "世界",
    "rank": "排名",
}


def resolve_cn_label(field_path: str) -> str:
    if field_path in EXACT_CN_LABELS:
        return EXACT_CN_LABELS[field_path]

    tokens = field_path.replace(".", "_").split("_")
    translated = "".join(TOKEN_CN_LABELS.get(token, token.upper() if token.isupper() else token) for token in tokens)
    return translated or field_path
